REINDEX INDEX idx_region_geom;
REINDEX INDEX idx_io_from_region;
REINDEX INDEX idx_io_from_product;
REINDEX INDEX idx_io_allocation;
REINDEX INDEX idx_io_to_region;
REINDEX INDEX idx_io_to_product;
REINDEX INDEX idx_io_year;
REINDEX INDEX idx_y_from_region;
REINDEX INDEX idx_y_to_region;
REINDEX INDEX idx_y_product;
REINDEX INDEX idx_y_year;
REINDEX INDEX idx_y_element;
REINDEX INDEX idx_ei_from_region;
REINDEX INDEX idx_ei_from_product;
REINDEX INDEX idx_ei_year;
REINDEX INDEX idx_ei_env_factor;

VACUUM;
ANALYZE type;
ANALYZE element;
ANALYZE final_demand;
ANALYZE region_cluster;
ANALYZE region;
ANALYZE region_aggregate;
ANALYZE product_unit;
ANALYZE product;
ANALYZE allocation;
ANALYZE env_factor;
ANALYZE env_factor_unit;
ANALYZE "input-output_leontief";
ANALYZE region_cluster_region;
ANALYZE product_group;
ANALYZE env_intensity;